name: Changesets

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Create Release Pull Request or Start release (tag)
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun run publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_CHANGESET }}
